const GET_POKEMONS = 'GET_POKEMONS';
const GET_NAMES = 'GET_NAMES';
const GET_TYPES = 'GET_TYPES';
const FILTER_BY_TYPE = 'FILTER_BY_TYPE';
const CREATED_DB = 'CREATED_DB';
const ORDER_ATTACK = 'ORDER_ATTACK';
const ORDER_ALPHABETICAL = 'ORDER_ALPHABETICAL';
const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL';
const LOADER_FALSE = 'LOADER_FALSE';
const LOADER_TRUE = 'LOADER_TRUE';


export {
    GET_POKEMONS,
    GET_NAMES,
    GET_TYPES,
    FILTER_BY_TYPE,
    CREATED_DB,
    ORDER_ATTACK,
    ORDER_ALPHABETICAL,
    GET_POKEMON_DETAIL,
    LOADER_FALSE,
    LOADER_TRUE
}